# Generated by Django 5.0.1 on 2024-01-16 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbv', '0002_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='e_date', to='cbv.student'),
        ),
    ]
